// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9MecyORphoDyoe5kIKGOOf9eupIRkF8',
    appId: '1:66230938641:web:ccf5a83b0a0b1c7c6055b0',
    messagingSenderId: '66230938641',
    projectId: 'khodari-bluemill',
    authDomain: 'khodari-bluemill.firebaseapp.com',
    storageBucket: 'khodari-bluemill.appspot.com',
    measurementId: 'G-CPJB51928K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC9o8EhFLKdqChcqjZxY4VMEdZfF63P7k',
    appId: '1:66230938641:android:c3ef81daa79bebfa6055b0',
    messagingSenderId: '66230938641',
    projectId: 'khodari-bluemill',
    storageBucket: 'khodari-bluemill.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvlcpScSpUXJJU3pFawAigNwdZfVONP4',
    appId: '1:66230938641:ios:498ecb37bc1864946055b0',
    messagingSenderId: '66230938641',
    projectId: 'khodari-bluemill',
    storageBucket: 'khodari-bluemill.appspot.com',
    iosBundleId: 'com.example.khodariTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsvlcpScSpUXJJU3pFawAigNwdZfVONP4',
    appId: '1:66230938641:ios:7f1f4b711abf760f6055b0',
    messagingSenderId: '66230938641',
    projectId: 'khodari-bluemill',
    storageBucket: 'khodari-bluemill.appspot.com',
    iosBundleId: 'com.example.khodariTest.RunnerTests',
  );
}
